INFO:
  title: HuMoRapiD
  intro: API-Wrapper for Human Motion Diffusion Nodels

VERSION: 1.0.0

SERVER:
  host: 0.0.0.0
  port: 8080
  log_level: info
  workers: 

ICON:
  url: assets/favicon.ico

TAGS:
  - name: Main
    description: Main API functions.
  - name: Configuration
    description: Configuration for Models, Datasets, etc.
  - name: Resources
    description: Resources Control, especially GPU.
  - name: Test
    description: Some tests for API, unnecessary for main functions.

ARGUMENTS:

  DEPENDENCY_DIR: "path/to/dependencies, which contains sub-folders such as assets, body_models, glove, kit, t2m."
  SMPL_DATA_ROOT: "path/to/body_models, which contains sub-folders such as smpl, smplh, smplx, mano."

  MODEL_DIR: "Path to folder containing model checkpoints"
  cuda_device: "GPU Id to load Model(s) into."
  cpu_offload: "Whether to offload all models to CPU, reducing memory usage with a low impact on performance.\nMore details: find `enable_model_cpu_offload` in `https://huggingface.co/docs/diffusers/en/api/pipelines/overview`"

  prompt_positive: "Description of what you desire to INCLUDE in output"
  prompt_negative: "Description of what you desire to EXCLUDE in output"
  prompt_multiple: "Whether to use multiple prompts, to describe a sequence of actions."
  prompt_incommon: "Description of the context of what 2 persons are doing"
  prompt_person_1: "Detail of what the 1st person is doing"
  prompt_person_2: "Detail of what the 2nd person is doing"

  action_name: "Name of (pre-defined) action to be used, rather than using prompt"
  model_ckpt: "Name of model checkpoint to load"
